version: '3'
services:
  timer:
    image: phpswoole/swoole
    container_name: tasker
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    ports:
      - "9501:9501"
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - back
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6380:6379"
    networks:
      - back

networks:
  back:
